/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.ResultSetMetaData;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author aswan
 */
public class Booking extends javax.swing.JFrame {
    Connection con = null;
    PreparedStatement ps = null;
    ResultSet rs = null, rs1 = null;
    Statement st = null, st1 = null;
    DefaultTableModel dtm;
    /**
     * Creates new form Booking
     */
    public Booking() {
        initComponents();
        GetRooms();
        GetPelanggan();
        ShowBooking();
        tfBiaya.setEditable(false);
    }
        
    private void GetRooms(){
        try {
            String stat = "Free";
            con = DriverManager.getConnection("jdbc:mysql://localhost/hotels", "root", "");
            st = con.createStatement();
            rs = st.executeQuery("SELECT * FROM room where status_kamar='"+stat+"'");
            
            while(rs.next()){
                int R = rs.getInt("nomor_kamar");
                cbKamar.addItem(""+R);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Room.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void UpdateRoom(){
        try {
                String stat = "Booked";
                con = DriverManager.getConnection("jdbc:mysql://localhost/hotels", "root", "");
                PreparedStatement pres = con.prepareStatement("UPDATE room set status_kamar=? where nomor_kamar=?");
                pres.setString(1, stat);
                pres.setInt(2, Integer.valueOf(cbKamar.getSelectedItem().toString()));                
                
                int row = pres.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data Kamar telah Diperbarui!");
                con.close();
                
            } catch (SQLException ex) {
                Logger.getLogger(Room.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    
    private void UpdateToFree(){
        try {
                String stat = "Free";
                con = DriverManager.getConnection("jdbc:mysql://localhost/hotels", "root", "");
                PreparedStatement pres = con.prepareStatement("UPDATE room set status_kamar=? where nomor_kamar=?");
                pres.setString(1, stat);
                pres.setInt(2, r);                
                
                int row = pres.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data Kamar telah Diperbarui!");
                con.close();
                
            } catch (SQLException ex) {
                Logger.getLogger(Room.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    
    private void GetPelanggan(){
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/hotels", "root", "");
            st = con.createStatement();
            rs = st.executeQuery("SELECT * FROM customer");
            
            while(rs.next()){
                int R = rs.getInt("id_pelanggan");
                cbNama.addItem(""+R);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Room.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    int bk;
    private void GetBiaya(){
        try {
            st1 = con.createStatement();
            rs1 = st1.executeQuery("SELECT harga FROM room WHERE nomor_kamar="+cbKamar.getSelectedItem().toString());
            rs1.next();            
            bk = rs1.getInt(1);
            tfBiaya.setText(""+bk);
            
        } catch (SQLException ex) {
            Logger.getLogger(Room.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfDurasi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        BookingTable = new javax.swing.JTable();
        btcCancel = new javax.swing.JButton();
        btnBook = new javax.swing.JButton();
        DateBooking = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        tfBiaya = new javax.swing.JTextField();
        cbKamar = new javax.swing.JComboBox<>();
        cbNama = new javax.swing.JComboBox<>();
        btnFetch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(24, 118, 235));

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/booking.png"))); // NOI18N
        jLabel1.setText("Manage Booking");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/back-button.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel6)
                .addGap(169, 169, 169)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel2.setBackground(new java.awt.Color(24, 118, 235));
        jLabel2.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(24, 118, 235));
        jLabel2.setText("Nomor Kamar");

        jLabel3.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(24, 118, 235));
        jLabel3.setText("ID Pelanggan");

        jLabel4.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(24, 118, 235));
        jLabel4.setText("Tanggal Booking");

        jLabel5.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(24, 118, 235));
        jLabel5.setText("Durasi dalam Sehari");

        tfDurasi.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        tfDurasi.setForeground(new java.awt.Color(24, 118, 235));
        tfDurasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDurasiActionPerformed(evt);
            }
        });

        BookingTable.setBackground(new java.awt.Color(24, 118, 235));
        BookingTable.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        BookingTable.setForeground(new java.awt.Color(255, 255, 255));
        BookingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id Booking", "Nomor Kamar", "Id Pelanggan", "Tanggal", "Durasi", "Biaya"
            }
        ));
        BookingTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookingTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(BookingTable);

        btcCancel.setBackground(new java.awt.Color(255, 51, 51));
        btcCancel.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btcCancel.setForeground(new java.awt.Color(255, 255, 255));
        btcCancel.setText("Cancel");
        btcCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcCancelActionPerformed(evt);
            }
        });

        btnBook.setBackground(new java.awt.Color(24, 118, 235));
        btnBook.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnBook.setForeground(new java.awt.Color(255, 255, 255));
        btnBook.setText("Book");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(24, 118, 235));
        jLabel7.setText("Biaya");

        tfBiaya.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        tfBiaya.setForeground(new java.awt.Color(24, 118, 235));
        tfBiaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBiayaActionPerformed(evt);
            }
        });

        cbKamar.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cbKamar.setForeground(new java.awt.Color(24, 118, 235));
        cbKamar.setSelectedIndex(-1);
        cbKamar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbKamarItemStateChanged(evt);
            }
        });

        cbNama.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cbNama.setForeground(new java.awt.Color(24, 118, 235));
        cbNama.setSelectedIndex(-1);

        btnFetch.setBackground(new java.awt.Color(24, 118, 235));
        btnFetch.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnFetch.setForeground(new java.awt.Color(255, 255, 255));
        btnFetch.setText("Cek Total Biaya");
        btnFetch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFetchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnFetch)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btcCancel))
                            .addComponent(tfBiaya)
                            .addComponent(tfDurasi)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(DateBooking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbKamar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbNama, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(1, 1, 1)
                        .addComponent(cbKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(1, 1, 1)
                        .addComponent(cbNama, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(1, 1, 1)
                        .addComponent(DateBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(1, 1, 1)
                        .addComponent(tfDurasi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(btnFetch, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfBiaya, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btcCancel)
                            .addComponent(btnBook, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        new Dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void tfDurasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDurasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDurasiActionPerformed

    int key = 0;
    private void btcCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcCancelActionPerformed
        // TODO add your handling code here:
        if(key == 0){
            JOptionPane.showMessageDialog(this, "Pilih Booking!!");
        }else{
            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost/hotels", "root", "");
                PreparedStatement pres = con.prepareStatement("DELETE FROM booking where nomor_booking = ?");
                pres.setInt(1, key);               
                int row = pres.executeUpdate();
                JOptionPane.showMessageDialog(this, "Booking dihapus!");
                con.close();
                ShowBooking();
                UpdateToFree();
                cbKamar.removeAllItems();
                GetRooms();
                
            } catch (SQLException ex) {
                Logger.getLogger(Room.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btcCancelActionPerformed
    
    private void ShowBooking(){
        int column;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/hotels", "root", "");
            st = con.createStatement();
            rs = st.executeQuery("SELECT * FROM booking");
            
            ResultSetMetaData rsd = rs.getMetaData();
            column = rsd.getColumnCount();
            
            dtm = (DefaultTableModel)BookingTable.getModel();
            dtm.setRowCount(0);
            
            while(rs.next()){
                Vector v2 = new Vector();
                
                for(int i=1; i<=column; i++){
                    v2.add(rs.getString("nomor_booking"));
                    v2.add(rs.getString("nomor_kamar"));
                    v2.add(rs.getString("id_pelanggan"));
                    v2.add(rs.getString("tgl_booking"));
                    v2.add(rs.getString("durasi"));
                    v2.add(rs.getString("biaya"));
                }
                dtm.addRow(v2);
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Room.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    int bid;
    private void CountBookings(){
        try {
            st = con.createStatement();
            rs = st.executeQuery("SELECT Max(nomor_booking) FROM booking");
            rs.next();
            bid = rs.getInt(1)+1;
            
        } catch (SQLException ex) {
            Logger.getLogger(Room.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }
    
    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        // TODO add your handling code here:
        if(cbKamar.getSelectedIndex() == -1 || cbNama.getSelectedIndex() == -1 || tfDurasi.getText().isEmpty() || tfBiaya.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Data Tidak Boleh Kosong!");
        }else{
            try {
                String Bdate = DateBooking.getDate().toString().substring(0, 11);
                CountBookings();
                con = DriverManager.getConnection("jdbc:mysql://localhost/hotels", "root", "");
                PreparedStatement pres = con.prepareStatement("INSERT INTO booking values(?,?,?,?,?,?)");
                
                pres.setInt(1, bid);
                pres.setInt(2, Integer.valueOf(cbKamar.getSelectedItem().toString()));
                pres.setInt(3, Integer.valueOf(cbNama.getSelectedItem().toString()));
                pres.setString(4, Bdate);
                pres.setInt(5, Integer.valueOf(tfDurasi.getText().toString()));
                pres.setInt(6, Integer.valueOf(tfBiaya.getText().toString()));
                
                int row = pres.executeUpdate();
                JOptionPane.showMessageDialog(this, "Kamar telah Dipesan!");
                con.close();
                ShowBooking();
                UpdateRoom();
                cbKamar.removeAllItems();
                GetRooms();
                
            } catch (SQLException ex) {
                Logger.getLogger(Room.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnBookActionPerformed

    private void tfBiayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBiayaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBiayaActionPerformed

    private void cbKamarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbKamarItemStateChanged
        // TODO add your handling code here:
        GetBiaya();
    }//GEN-LAST:event_cbKamarItemStateChanged

    private void btnFetchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFetchActionPerformed
        // TODO add your handling code here:
        int totalJumlah = bk * Integer.valueOf(tfDurasi.getText().toString());
        tfBiaya.setText(""+totalJumlah);
    }//GEN-LAST:event_btnFetchActionPerformed

    int r;
    private void BookingTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookingTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) BookingTable.getModel();
        int MyIndex = BookingTable.getSelectedRow();
        key = Integer.valueOf(model.getValueAt(MyIndex, 0).toString());
        r = Integer.valueOf(model.getValueAt(MyIndex, 1).toString());
        cbKamar.setSelectedItem(model.getValueAt(MyIndex, 1).toString());
        cbNama.setSelectedItem(model.getValueAt(MyIndex, 2).toString());
        tfDurasi.setText(model.getValueAt(MyIndex, 4).toString());
        tfBiaya.setText(model.getValueAt(MyIndex, 5).toString());
    }//GEN-LAST:event_BookingTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Booking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BookingTable;
    private com.toedter.calendar.JDateChooser DateBooking;
    private javax.swing.JButton btcCancel;
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnFetch;
    private javax.swing.JComboBox<String> cbKamar;
    private javax.swing.JComboBox<String> cbNama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tfBiaya;
    private javax.swing.JTextField tfDurasi;
    // End of variables declaration//GEN-END:variables
}
