/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.ResultSetMetaData;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aswan
 */
public class Room extends javax.swing.JFrame {
    
    Connection con = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    Statement st = null;
    DefaultTableModel dtm;
    /**
     * Creates new form Room
     */
    public Room() {
        initComponents();
        ShowRooms();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbKategori = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cbStatus = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        tfHarga = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        RoomTable = new javax.swing.JTable();
        ButtonEdit = new javax.swing.JButton();
        ButtonTambah = new javax.swing.JButton();
        ButtonHapus = new javax.swing.JButton();
        KategoriFilter = new javax.swing.JComboBox<>();
        StatusFilter = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(24, 118, 235));

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/bed.png"))); // NOI18N
        jLabel1.setText("Manage Room");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/back-button.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(216, 216, 216))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(14, 14, 14))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setBackground(new java.awt.Color(24, 118, 235));
        jLabel2.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(24, 118, 235));
        jLabel2.setText("Nama Kamar");

        tfNama.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        tfNama.setForeground(new java.awt.Color(24, 118, 235));
        tfNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(24, 118, 235));
        jLabel3.setText("Kategori");

        cbKategori.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cbKategori.setForeground(new java.awt.Color(24, 118, 235));
        cbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VIP", "Double Bed", "Single Bed", "Family" }));
        cbKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKategoriActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(24, 118, 235));
        jLabel4.setText("Status");

        cbStatus.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cbStatus.setForeground(new java.awt.Color(24, 118, 235));
        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Free", "Booked" }));
        cbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbStatusActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(24, 118, 235));
        jLabel5.setText("Harga");

        tfHarga.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        tfHarga.setForeground(new java.awt.Color(24, 118, 235));
        tfHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHargaActionPerformed(evt);
            }
        });

        RoomTable.setBackground(new java.awt.Color(24, 118, 235));
        RoomTable.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        RoomTable.setForeground(new java.awt.Color(255, 255, 255));
        RoomTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "Nama", "Tipe", "Status", "Harga"
            }
        ));
        RoomTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RoomTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(RoomTable);

        ButtonEdit.setBackground(new java.awt.Color(24, 118, 235));
        ButtonEdit.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        ButtonEdit.setForeground(new java.awt.Color(255, 255, 255));
        ButtonEdit.setText("Edit");
        ButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditActionPerformed(evt);
            }
        });

        ButtonTambah.setBackground(new java.awt.Color(24, 118, 235));
        ButtonTambah.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        ButtonTambah.setForeground(new java.awt.Color(255, 255, 255));
        ButtonTambah.setText("Tambah");
        ButtonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTambahActionPerformed(evt);
            }
        });

        ButtonHapus.setBackground(new java.awt.Color(255, 0, 0));
        ButtonHapus.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        ButtonHapus.setForeground(new java.awt.Color(255, 255, 255));
        ButtonHapus.setText("Hapus");
        ButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHapusActionPerformed(evt);
            }
        });

        KategoriFilter.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        KategoriFilter.setForeground(new java.awt.Color(24, 118, 235));
        KategoriFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VIP", "Double Bed", "Single Bed", "Family" }));
        KategoriFilter.setPreferredSize(new java.awt.Dimension(91, 28));
        KategoriFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KategoriFilterActionPerformed(evt);
            }
        });

        StatusFilter.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        StatusFilter.setForeground(new java.awt.Color(24, 118, 235));
        StatusFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Free", "Booked" }));
        StatusFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusFilterActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(24, 118, 235));
        jLabel7.setText("Refresh");

        btnRefresh.setBackground(new java.awt.Color(24, 118, 235));
        btnRefresh.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(cbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(tfHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ButtonTambah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ButtonHapus)
                        .addGap(29, 29, 29)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(KategoriFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(StatusFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRefresh)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KategoriFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StatusFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(1, 1, 1)
                        .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(1, 1, 1)
                        .addComponent(cbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(1, 1, 1)
                        .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(1, 1, 1)
                        .addComponent(tfHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonTambah)
                            .addComponent(ButtonEdit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonHapus)
                        .addGap(100, 100, 100))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ShowRooms(){
        int column;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/hotels", "root", "");
            st = con.createStatement();
            rs = st.executeQuery("SELECT * FROM room ");
            
            ResultSetMetaData rsd = rs.getMetaData();
            column = rsd.getColumnCount();
            
            dtm = (DefaultTableModel)RoomTable.getModel();
            dtm.setRowCount(0);
            
            while(rs.next()){
                Vector v2 = new Vector();
                
                for(int i=1; i<=column; i++){
                    v2.add(rs.getString("nomor_kamar"));
                    v2.add(rs.getString("nama_kamar"));
                    v2.add(rs.getString("tipe_kamar"));
                    v2.add(rs.getString("status_kamar"));
                    v2.add(rs.getString("harga"));
                }
                dtm.addRow(v2);
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Room.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void FilterByKategori(){
        int column;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/hotels", "root", "");
            st = con.createStatement();
            rs = st.executeQuery("SELECT * FROM room WHERE tipe_kamar like '"+KategoriFilter.getSelectedItem().toString()+"%'");
            
            ResultSetMetaData rsd = rs.getMetaData();
            column = rsd.getColumnCount();
            
            dtm = (DefaultTableModel)RoomTable.getModel();
            dtm.setRowCount(0);
            
            while(rs.next()){
                Vector v2 = new Vector();
                
                for(int i=1; i<=column; i++){
                    v2.add(rs.getString("nomor_kamar"));
                    v2.add(rs.getString("nama_kamar"));
                    v2.add(rs.getString("tipe_kamar"));
                    v2.add(rs.getString("status_kamar"));
                    v2.add(rs.getString("harga"));
                }
                dtm.addRow(v2);
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Room.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void FilterByStatus(){
        int column;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/hotels", "root", "");
            st = con.createStatement();
            rs = st.executeQuery("SELECT * FROM room WHERE status_kamar like '"+StatusFilter.getSelectedItem().toString()+"%'");
            
            ResultSetMetaData rsd = rs.getMetaData();
            column = rsd.getColumnCount();
            
            dtm = (DefaultTableModel)RoomTable.getModel();
            dtm.setRowCount(0);
            
            while(rs.next()){
                Vector v2 = new Vector();
                
                for(int i=1; i<=column; i++){
                    v2.add(rs.getString("nomor_kamar"));
                    v2.add(rs.getString("nama_kamar"));
                    v2.add(rs.getString("tipe_kamar"));
                    v2.add(rs.getString("status_kamar"));
                    v2.add(rs.getString("harga"));
                }
                dtm.addRow(v2);
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Room.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    int rid;
    private void CountRooms(){
        try {
            st = con.createStatement();
            rs = st.executeQuery("SELECT Max(nomor_kamar) FROM room");
            rs.next();
            rid = rs.getInt(1)+1;
            
        } catch (SQLException ex) {
            Logger.getLogger(Room.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }
    
    private void tfNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamaActionPerformed

    private void cbKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbKategoriActionPerformed

    private void cbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbStatusActionPerformed

    private void tfHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHargaActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        new Dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void ButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditActionPerformed
        // TODO add your handling code here:
        if(tfNama.getText().isEmpty() || cbKategori.getSelectedIndex() == -1 || cbStatus.getSelectedIndex() == -1 || tfHarga.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Data Tidak Boleh Kosong!");
        }else{
            try {
                CountRooms();
                con = DriverManager.getConnection("jdbc:mysql://localhost/hotels", "root", "");
                PreparedStatement pres = con.prepareStatement("UPDATE room set nama_kamar=?, tipe_kamar=?, status_kamar=?, harga=? where nomor_kamar=?");
                pres.setInt(5, key);
                pres.setString(1, tfNama.getText().toString());
                pres.setString(2, cbKategori.getSelectedItem().toString());
                pres.setString(3, cbStatus.getSelectedItem().toString());
                pres.setInt(4, Integer.valueOf(tfHarga.getText().toString()));
                int row = pres.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data Kamar telah Diperbarui!");
                con.close();
                ShowRooms();
                
            } catch (SQLException ex) {
                Logger.getLogger(Room.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_ButtonEditActionPerformed

    private void ButtonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTambahActionPerformed
        // TODO add your handling code here:
        if(tfNama.getText().isEmpty() || cbKategori.getSelectedIndex() == -1 || cbStatus.getSelectedIndex() == -1 || tfHarga.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Data Tidak Boleh Kosong!");
        }else{
            try {
                CountRooms();
                con = DriverManager.getConnection("jdbc:mysql://localhost/hotels", "root", "");
                PreparedStatement pres = con.prepareStatement("INSERT INTO room values(?,?,?,?,?)");
                pres.setInt(1, rid);
                pres.setString(2, tfNama.getText().toString());
                pres.setString(3, cbKategori.getSelectedItem().toString());
                pres.setString(4, cbStatus.getSelectedItem().toString());
                pres.setInt(5, Integer.valueOf(tfHarga.getText().toString()));
                int row = pres.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data Kamar telah Ditambahkan!");
                con.close();
                ShowRooms();
                
            } catch (SQLException ex) {
                Logger.getLogger(Room.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_ButtonTambahActionPerformed
    
    int key=0;
    private void ButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHapusActionPerformed
        // TODO add your handling code here:
        if(key == 0){
            JOptionPane.showMessageDialog(this, "Pilih Kamar!!");
        }else{
            try {
                CountRooms();
                con = DriverManager.getConnection("jdbc:mysql://localhost/hotels", "root", "");
                PreparedStatement pres = con.prepareStatement("DELETE FROM room where nomor_kamar = ?");
                pres.setInt(1, key);               
                int row = pres.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data Kamar telah Dihapus!");
                con.close();
                ShowRooms();
                
            } catch (SQLException ex) {
                Logger.getLogger(Room.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_ButtonHapusActionPerformed

    private void RoomTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoomTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) RoomTable.getModel();
        int MyIndex = RoomTable.getSelectedRow();
        key = Integer.valueOf(model.getValueAt(MyIndex, 0).toString());
        tfNama.setText(model.getValueAt(MyIndex, 1).toString());
        cbKategori.setSelectedItem(model.getValueAt(MyIndex, 2).toString());
        cbStatus.setSelectedItem(model.getValueAt(MyIndex, 3).toString());
        tfHarga.setText(model.getValueAt(MyIndex, 4).toString());
    }//GEN-LAST:event_RoomTableMouseClicked

    private void KategoriFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KategoriFilterActionPerformed
        // TODO add your handling code here:
        FilterByKategori();
    }//GEN-LAST:event_KategoriFilterActionPerformed

    private void StatusFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusFilterActionPerformed
        // TODO add your handling code here:
        FilterByStatus();
    }//GEN-LAST:event_StatusFilterActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        ShowRooms();
        KategoriFilter.setSelectedIndex(0);
        StatusFilter.setSelectedIndex(0);
    }//GEN-LAST:event_btnRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Room().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonEdit;
    private javax.swing.JButton ButtonHapus;
    private javax.swing.JButton ButtonTambah;
    private javax.swing.JComboBox<String> KategoriFilter;
    private javax.swing.JTable RoomTable;
    private javax.swing.JComboBox<String> StatusFilter;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JComboBox<String> cbKategori;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tfHarga;
    private javax.swing.JTextField tfNama;
    // End of variables declaration//GEN-END:variables
}
